StructDiff(struct('a', 1), struct('a', 1))
StructDiff(struct('a', 1, 'b', struct('c', 2, 'd', 5)), ...
           struct('a', 1, 'd', 3))
StructDiff(struct('d', struct('a', 1, 'b', struct('c', 2, 'd', 5)), 'c', 2), ...
           struct('d', struct('a', 1, 'b', 3), 'c', 2))
StructDiff(struct('d', struct('a', 1, 'b', struct('c', 2, 'd', 5)), 'c', 2), ...
           struct('d', struct('a', 1, 'b', 3), 'c', 3))
