name: Test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  testing:
    name: "Test MATLAB ${{matrix.release}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [R2020a, R2020b, R2021a, latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{matrix.release}}

    - name: Test
      uses: matlab-actions/run-tests@v1
      with:
        source-folder: .
        select-by-folder: test
        code-coverage-cobertura: coverage.xml

    - uses: codecov/codecov-action@v2
      with:
        file: coverage.xml
