name: Test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Test
      uses: matlab-actions/run-command@v1
      with:
        command: addpath('test'), runtests
